# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2021-06-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satilanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genel_total', models.CharField(max_length=10, null=True, verbose_name='Total ')),
                ('satilma_tarihi', models.DateField(auto_now_add=True, null=True, verbose_name='Oyun \xe7\u0131k\u0131\u015f tarihi')),
            ],
            options={
                'verbose_name': 'Sat\u0131\u015f',
                'verbose_name_plural': 'Sat\u0131lanlar',
            },
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(null=True, verbose_name='Adet ')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.KullaniciBilgi')),
                ('urun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Urunler')),
            ],
            options={
                'verbose_name': 'Sepet',
                'verbose_name_plural': 'Sepetler',
            },
        ),
        migrations.AddField(
            model_name='satilanlar',
            name='sepet',
            field=models.ManyToManyField(to='home.Sepet'),
        ),
    ]
